/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cvsystem;

import java.awt.Image;
import java.sql.Connection;
import java.sql.DriverManager;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Busra
 */
public class employee extends javax.swing.JFrame {

    /**
     * Creates new form employee
     * 
     */
     private login parentw;
     public employee (login parent ) {
         this.parentw = parent;
     
    }

    public employee(String incoming) {
        initComponents();
         jLabel1.setText(incoming);			//set the text with coming data
         jLabel1.setVisible(false);				//hide that
		 
         image.setVisible(true);				//make visible the image
         employeename.setVisible(true);			//make visible the name
         employeemail.setVisible(true);			//make visible the mail
         employeeid.setVisible(true);			//make visible the id
         forqualification.setVisible(false);			//hide that
         foredinfo.setVisible(false);					//hide that
         
         forwexp.setVisible(false);						//hide that

     
         
         
       jScrollPane1.setVisible(false);				//hide that
       jScrollPane2.setVisible(false);				//hide that
       jScrollPane5.setVisible(false);				//hide that
      jTable1.setVisible(false); 					//hide that
       jScrollPane4.setVisible(false);				//hide that
       
      

 Connection connect;		//identify the connection	
  Statement st;				//identify the statement
  ResultSet result;			//identify the result

try
                        {
                            
                        jLabel1.setText(incoming);		//set text with coming data
                            //connection and statement information
							connect = DriverManager.getConnection("jdbc:mysql://localhost:3306/cvsystem?useUnicode=true&characterEncoding=UTF-8", "busra", "0987");
                            st = connect.createStatement();
            result = st.executeQuery("SELECT `memberimage`,`memberfullname`,`memberID`,`qualification`, `wexperience`,`e-mail`,`education` FROM `members` WHERE `memberID` = '"+incoming+"'");
              //result statement
           
            while(result.next()){			//while statement
                
                byte[] img = result.getBytes(1);		//create a byte variable for the image
            ImageIcon imageIcon = new ImageIcon(new ImageIcon(img).getImage().getScaledInstance(image.getWidth(), image.getHeight(), Image.SCALE_DEFAULT));	//the default statement
            image.setIcon(imageIcon);			//set the icon
            employeename.setText(result.getString(2));		//set the name
            employeemail.setText(result.getString(6));		//set the mail
            employeeid.setText(result.getString(3));		//set the id
            forqualification.setText(result.getString(4));		//set the qualification info
            foredinfo.setText(result.getString(7));				//set the education info
            forwexp.setText(result.getString(5));				//set the experience info
            }
           
           
            
             }
                          catch (SQLException ex) {
            Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
        }





         
         
    }
    
    private employee () {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        image = new javax.swing.JLabel();
        employeename = new javax.swing.JLabel();
        employeemail = new javax.swing.JLabel();
        employeeid = new javax.swing.JLabel();
        workexp = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        edinfo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        forqualification = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        forwexp = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        foredinfo = new javax.swing.JTextPane();
        certificates = new javax.swing.JButton();
        qualifications = new javax.swing.JButton();
        emplogout = new javax.swing.JButton();
        employeeback = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("E-CV");
        setMinimumSize(new java.awt.Dimension(1366, 768));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });
        getContentPane().setLayout(null);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(100, 40, 100, 25);
        getContentPane().add(image);
        image.setBounds(20, 40, 200, 160);

        employeename.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        getContentPane().add(employeename);
        employeename.setBounds(260, 50, 140, 20);

        employeemail.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        getContentPane().add(employeemail);
        employeemail.setBounds(260, 90, 140, 20);

        employeeid.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        getContentPane().add(employeeid);
        employeeid.setBounds(260, 130, 140, 20);

        workexp.setText("Work Experience");
        workexp.setPreferredSize(new java.awt.Dimension(150, 25));
        workexp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                workexpActionPerformed(evt);
            }
        });
        getContentPane().add(workexp);
        workexp.setBounds(900, 290, 210, 25);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
            },
            new String [] {
            }
        ));
        jTable1.setEnabled(false);
        jScrollPane5.setViewportView(jTable1);

        getContentPane().add(jScrollPane5);
        jScrollPane5.setBounds(380, 320, 500, 250);

        edinfo.setText("Educational Information");
        edinfo.setMaximumSize(new java.awt.Dimension(150, 25));
        edinfo.setMinimumSize(new java.awt.Dimension(150, 25));
        edinfo.setPreferredSize(new java.awt.Dimension(150, 25));
        edinfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edinfoActionPerformed(evt);
            }
        });
        getContentPane().add(edinfo);
        edinfo.setBounds(220, 290, 150, 25);

        forqualification.setEditable(false);
        forqualification.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        jScrollPane1.setViewportView(forqualification);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(60, 320, 150, 250);

        jScrollPane4.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        jScrollPane4.setMinimumSize(new java.awt.Dimension(300, 200));
        jScrollPane4.setPreferredSize(new java.awt.Dimension(300, 250));

        forwexp.setEditable(false);
        forwexp.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        forwexp.setMinimumSize(new java.awt.Dimension(300, 200));
        forwexp.setPreferredSize(new java.awt.Dimension(300, 200));
        jScrollPane4.setViewportView(forwexp);

        getContentPane().add(jScrollPane4);
        jScrollPane4.setBounds(900, 320, 210, 250);

        jScrollPane2.setMinimumSize(new java.awt.Dimension(200, 200));
        jScrollPane2.setPreferredSize(new java.awt.Dimension(300, 250));

        foredinfo.setEditable(false);
        foredinfo.setBackground(new java.awt.Color(204, 204, 255));
        foredinfo.setBorder(null);
        foredinfo.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        foredinfo.setMinimumSize(new java.awt.Dimension(300, 200));
        foredinfo.setPreferredSize(new java.awt.Dimension(300, 200));
        jScrollPane2.setViewportView(foredinfo);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(220, 320, 150, 250);

        certificates.setText("Positions/Certificates");
        certificates.setMaximumSize(new java.awt.Dimension(150, 25));
        certificates.setMinimumSize(new java.awt.Dimension(150, 25));
        certificates.setPreferredSize(new java.awt.Dimension(150, 25));
        certificates.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                certificatesActionPerformed(evt);
            }
        });
        getContentPane().add(certificates);
        certificates.setBounds(380, 290, 500, 25);

        qualifications.setText("Qualifications");
        qualifications.setMaximumSize(new java.awt.Dimension(150, 25));
        qualifications.setMinimumSize(new java.awt.Dimension(150, 25));
        qualifications.setPreferredSize(new java.awt.Dimension(150, 25));
        qualifications.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qualificationsActionPerformed(evt);
            }
        });
        getContentPane().add(qualifications);
        qualifications.setBounds(60, 290, 150, 25);

        emplogout.setBackground(new java.awt.Color(255, 0, 51));
        emplogout.setText("LOGOUT");
        emplogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emplogoutActionPerformed(evt);
            }
        });
        getContentPane().add(emplogout);
        emplogout.setBounds(1180, 620, 130, 30);

        employeeback.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cvsystem/IMG-20171215-WA0007.jpg"))); // NOI18N
        getContentPane().add(employeeback);
        employeeback.setBounds(0, 0, 1366, 768);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        employeeback.setSize(this.getSize());
    }//GEN-LAST:event_formComponentResized

    private void workexpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_workexpActionPerformed
         forqualification.setVisible(false);    // hide that
         foredinfo.setVisible(false);       // hide that
    
         forwexp.setVisible(true);      // make visible the work experience
          jScrollPane4.setVisible(true);     // make visible the panel
         
         
       jScrollPane1.setVisible(false);     // hide that
       jScrollPane2.setVisible(false);     // hide that
      jScrollPane5.setVisible(false);     // hide that
         jTable1.setVisible(false);         // hide that
      
    }//GEN-LAST:event_workexpActionPerformed

    private void qualificationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qualificationsActionPerformed
        jScrollPane1.setVisible(true);          // make visible 
        forqualification.setVisible(true);        // make visible
        foredinfo.setVisible(false);           // hide that
       jScrollPane2.setVisible(false);         // hide that
     jScrollPane5.setVisible(false);         // hide that
         jTable1.setVisible(false);             // hide that
        forwexp.setVisible(false);             // hide that
          jScrollPane4.setVisible(false);            // hide that
    }//GEN-LAST:event_qualificationsActionPerformed

    private void edinfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edinfoActionPerformed
       forqualification.setVisible(false);                // hide that
         foredinfo.setVisible(true);                  // make visible
         jScrollPane1.setVisible(false);              // hide that
       jScrollPane2.setVisible(true);                // make visible
       jScrollPane5.setVisible(false);              // hide that
         jTable1.setVisible(false);                 // hide that
        forwexp.setVisible(false);                 // hide that
          jScrollPane4.setVisible(false);              // hide that
    }//GEN-LAST:event_edinfoActionPerformed

    private void certificatesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_certificatesActionPerformed
    
      forqualification.setVisible(false);           // hide that
         foredinfo.setVisible(false);                  // hide that
         
         
       jScrollPane1.setVisible(false);             // hide that
       jScrollPane2.setVisible(false);             // hide that 
      
       forwexp.setVisible(false);                      // hide that
          jScrollPane4.setVisible(false);             // hide that
          
          // try the connection and statement variables
          try {
              String inf=jLabel1.getText();		//get text from the label and put onto the variable
        Connection dc = DriverManager.getConnection("jdbc:mysql://localhost:3306/cvsystem?useUnicode=true&characterEncoding=UTF-8", "busra", "0987");
        Statement st = (Statement) dc.createStatement();
		//try the statement as a result and execute the query
        try(ResultSet rs = st.executeQuery("SELECT `brandname`,`position`,`year`,`referance`,`certificate` FROM `members_info` WHERE `memberID` = '"+inf+"'") ) { 
            int countt = rs.getMetaData().getColumnCount(); 			//get column data from the database
            DefaultTableModel tm = new DefaultTableModel();				//create a default table model
			
            for(int i = 1;i<=countt;i++)			//the for loop
                tm.addColumn(rs.getMetaData().getColumnName(i)); 		//add data to column and get the column names
					while(rs.next())			//while statement
                {
   
                    Object[] row = new Object[countt];			//create rows with objects
                    for(int i=1;i<=countt;i++)				//the for loop for incremental counter
                        row[i-1] = rs.getObject(i);			//align the rows according to the database
                    tm.addRow(row);				//add the data to the rows
                }
            jTable1.setModel(tm);					//set the model
        }
        dc.close();								//close the connection
    } catch (SQLException ex) {
            Logger.getLogger(employee.class.getName()).log(Level.SEVERE, null, ex);
    }
      jScrollPane5.setVisible(true);			//make visible
      jTable1.setVisible(true); 				//make visible
          
    }//GEN-LAST:event_certificatesActionPerformed

    private void emplogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emplogoutActionPerformed
       dispose();				//close the current page
            new login().setVisible(true);			//open the login page again
    }//GEN-LAST:event_emplogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new employee().setVisible(true);				//the current page
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton certificates;
    private javax.swing.JButton edinfo;
    private javax.swing.JButton emplogout;
    private javax.swing.JLabel employeeback;
    private javax.swing.JLabel employeeid;
    private javax.swing.JLabel employeemail;
    private javax.swing.JLabel employeename;
    private javax.swing.JTextPane foredinfo;
    private javax.swing.JTextPane forqualification;
    private javax.swing.JTextPane forwexp;
    private javax.swing.JLabel image;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton qualifications;
    private javax.swing.JButton workexp;
    // End of variables declaration//GEN-END:variables
}
