/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cvsystem;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Büşra
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    
     public login() {
 initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        warning1 = new javax.swing.JLabel();
        userid = new javax.swing.JTextField();
        employeelogin = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        hrid = new javax.swing.JTextField();
        HRlogin = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        adminid = new javax.swing.JTextField();
        adminlogin = new javax.swing.JButton();
        warning2 = new javax.swing.JLabel();
        adminpass = new javax.swing.JPasswordField();
        userpass = new javax.swing.JPasswordField();
        HRpass = new javax.swing.JPasswordField();
        warning3 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("E-CV");
        setMinimumSize(new java.awt.Dimension(1366, 768));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ID:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(550, 290, 20, 17);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Password:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(510, 320, 59, 17);

        warning1.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        warning1.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(warning1);
        warning1.setBounds(470, 390, 330, 30);

        userid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                useridActionPerformed(evt);
            }
        });
        getContentPane().add(userid);
        userid.setBounds(580, 290, 100, 25);

        employeelogin.setText("Login as Employee");
        employeelogin.setPreferredSize(new java.awt.Dimension(133, 25));
        employeelogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeloginActionPerformed(evt);
            }
        });
        getContentPane().add(employeelogin);
        employeelogin.setBounds(540, 350, 140, 25);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ID:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(750, 290, 20, 17);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Password:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(710, 320, 59, 17);
        getContentPane().add(hrid);
        hrid.setBounds(780, 290, 100, 25);

        HRlogin.setText("Login as HR");
        HRlogin.setPreferredSize(new java.awt.Dimension(133, 25));
        HRlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HRloginActionPerformed(evt);
            }
        });
        getContentPane().add(HRlogin);
        HRlogin.setBounds(740, 350, 140, 23);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("ID:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(60, 20, 20, 17);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Password:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 50, 60, 17);

        adminid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminidActionPerformed(evt);
            }
        });
        getContentPane().add(adminid);
        adminid.setBounds(90, 15, 100, 25);

        adminlogin.setText("Login as Admin");
        adminlogin.setMaximumSize(new java.awt.Dimension(153, 25));
        adminlogin.setMinimumSize(new java.awt.Dimension(153, 25));
        adminlogin.setPreferredSize(new java.awt.Dimension(153, 25));
        adminlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminloginActionPerformed(evt);
            }
        });
        getContentPane().add(adminlogin);
        adminlogin.setBounds(50, 80, 140, 25);

        warning2.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        warning2.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(warning2);
        warning2.setBounds(20, 130, 330, 30);
        getContentPane().add(adminpass);
        adminpass.setBounds(90, 45, 100, 25);
        getContentPane().add(userpass);
        userpass.setBounds(580, 320, 100, 25);
        getContentPane().add(HRpass);
        HRpass.setBounds(780, 320, 100, 25);

        warning3.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        warning3.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(warning3);
        warning3.setBounds(670, 390, 330, 30);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cvsystem/IMG-20171212-WA0005.jpg"))); // NOI18N
        getContentPane().add(background);
        background.setBounds(0, -2, 1366, 770);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
         background.setSize(this.getSize());			//set background by frame size 
    }//GEN-LAST:event_formComponentResized

    private void useridActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_useridActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_useridActionPerformed

    private void employeeloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeloginActionPerformed
     String userID = userid.getText();				//get user id and put on to variable
String userpassword = userpass.getText();			//get user password and put on to variable



 Connection connection;						//identify connection
        PreparedStatement ps;				//identify statement

try											//try the structure that it allows to log in of employee 
                        {
                            
                           //open the connection and identify the statement 
                            connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/cvsystem?useUnicode=true&characterEncoding=UTF-8", "busra", "0987");
							ps = connection.prepareStatement("SELECT `memberID`, `memberpass` FROM  `members` WHERE `memberID` = ? AND `memberpass` = ?");
                            ps.setString(1, userID);			//put the query result to variable of user id
            ps.setString(2, String.valueOf(userpassword));		//put the query result to variable of user pass
            ResultSet result = ps.executeQuery(); 				//execute the statement 
                           
                       if(result.next()){
                         
                                   
                            
				// if the result query is successful, then the structure works that's like
            JOptionPane.showMessageDialog(null, "You logged in");
            
         warning1.setVisible(false);			//hide first warning
         warning2.setVisible(false);			//hide second warning
         new employee (this).setVisible(false);		
         new employee (userID).setVisible(true);		//open the employee window 
         
         dispose();						//shut the current window
         
         
         
      }else {				//if the query is not successful, then the structure works that's like
         JOptionPane.showMessageDialog(null, "Something is wrong.");		//display the message
         warning1.setText("Please try again.");				//put the warning
         warning1.setVisible(true);						//make visible that
        warning2.setVisible(false);						//hide that
        warning3.setVisible(false);						//hide that
                                    
 
if ("".equals(userpassword) && "".equals(userID)) {			//if the areas are null
warning1.setText("Please, enter the ID and the password!");
userid.requestFocusInWindow();					//focus on user id area



} else if ("".equals(userID)) {					//if the user id area is null
warning1.setText("Please, enter the ID!");
userid.requestFocusInWindow();				//focus on user id area
	


} else if ("".equals(userpassword)) {			//if the user pass area is null
warning1.setText("Please, enter the password!");
userpass.requestFocusInWindow();				//focus on user pass area

} }
                         } catch (SQLException ex) {
            Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_employeeloginActionPerformed

    private void adminloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminloginActionPerformed
      String IDadmin = adminid.getText();			//get the admin id and put on to variable
String adminpassword = adminpass.getText();			//get the admin pass and put on to variable
    if (IDadmin.equalsIgnoreCase("busra") && adminpassword.equalsIgnoreCase("0987")) {		//the session control for authority login
         JOptionPane.showMessageDialog(null, "You logged in");			//display message when the entries are true
         warning2.setVisible(false);				//hide that
         warning1.setVisible(false);				//hide that
          
          new admin (this).setVisible(true);			//redirect to the admin page from login page
            dispose();									//shut the current window
      } else {										//if the entries are wrong, display these messages
         JOptionPane.showMessageDialog(null, "Something is wrong.");		//display the message
         warning2.setText("Please try again.");			//set the text to label
         warning2.setVisible(true);						//make visible that	
          warning1.setVisible(false);					//hide that

if ("".equals(adminpassword) && "".equals(IDadmin)) {						//if the areas are null
warning2.setText("Please, enter the ID and the password!");		//set text to label and display it
adminid.requestFocusInWindow();										//focus on admin id



} else if ("".equals(IDadmin)) {					//if the admin id area is null
warning2.setText("Please, enter the ID!");				//display it
adminid.requestFocusInWindow();						//focus on the admin id area



} else if ("".equals(adminpassword)) {					//if the pass area is null
warning2.setText("Please, enter the password!");			//display it
adminpass.requestFocusInWindow();						//focus on the pass area

} 
    }                                   
    }//GEN-LAST:event_adminloginActionPerformed

    private void HRloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HRloginActionPerformed
       String hrID = hrid.getText();				//get the hr id and put on the variable
String hrpassword = HRpass.getText();				//get the hr pass and put on the variable

 Connection connection;					//identify the connection
        PreparedStatement ps;			//identify the statement

try
                        {
                            
                           //open connection and identify the statement structure with a SQL query
                            connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/cvsystem?useUnicode=true&characterEncoding=UTF-8", "busra", "0987");
                            
                            //retrieve that match the entries with query
                            ps = connection.prepareStatement("SELECT `brandID`, `brandpass` FROM  `hrdept` WHERE `brandID` = ? AND `brandpass` = ?");
                            ps.setString(1, hrID);
            ps.setString(2, String.valueOf(hrpassword));
            ResultSet result = ps.executeQuery();		//execute the statement
                           
                       if(result.next()){
                         
                                   
                            
 
            JOptionPane.showMessageDialog(null, "You logged in");			//display the message 
            
         warning1.setVisible(false);			//hide that
         warning2.setVisible(false);			//hide that
         warning3.setVisible(false);			//hide that
         new hrdepartment (this).setVisible(false);			
         new hrdepartment (hrID).setVisible(true);		//open the HR DEPARTMENT page 	
         
         dispose();										//shut the current window page
         
         
         
      }else {
         JOptionPane.showMessageDialog(null, "Something is wrong.");			//display the message
         warning3.setText("Please try again.");									//set the text for showing the warning
         warning3.setVisible(true);											 //make visible
        warning2.setVisible(false);											//hide that
        warning1.setVisible(false);											//hide that
                                    
 
if ("".equals(hrpassword) && "".equals(hrID)) {					//if the areas are null
warning3.setText("Please, enter the ID and the password!");			//set the text and display it
hrid.requestFocusInWindow();										//focus on the area of hr id



} else if ("".equals(hrID)) {								//if the hr id is null
warning3.setText("Please, enter the ID!");				//set the text and display it
hrid.requestFocusInWindow();						//focus on the area of hr id 



} else if ("".equals(hrpassword)) {					//if the hr pass is null
warning3.setText("Please, enter the password!");			//set the text and display it
HRpass.requestFocusInWindow();						//focus on the pass area

} }
                         } catch (SQLException ex) {
            Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_HRloginActionPerformed

    private void adminidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adminidActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new login().setVisible(true);				//current page
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton HRlogin;
    private javax.swing.JPasswordField HRpass;
    private javax.swing.JTextField adminid;
    private javax.swing.JButton adminlogin;
    private javax.swing.JPasswordField adminpass;
    private javax.swing.JLabel background;
    private javax.swing.JButton employeelogin;
    private javax.swing.JTextField hrid;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField userid;
    private javax.swing.JPasswordField userpass;
    private javax.swing.JLabel warning1;
    private javax.swing.JLabel warning2;
    private javax.swing.JLabel warning3;
    // End of variables declaration//GEN-END:variables
}
